### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'finish'

### ISSUE THREAD

**Issue by bradengroom** [reddit/baseplate.py#394]
It seems like there's some scenario where `trace` can be set, but it is `None`
https://github.com/reddit/baseplate.py/blob/db9c1d7cddb1cb242546349e821cad0b0cbd6fce/baseplate/frameworks/pyramid/__init__.py#L35

I think we should change the check above to something like `if hasattr(request, "trace") and request.trace:`, but I'm not really sure how we end up in this state in the first place. This happens to our service when we get a request on a path that we can't decode (`/caf%E9/`). We have an exception view defined to catch the `pyramid.exceptions.URLDecodeError` as recommended by the pyramid docs here:
https://docs.pylonsproject.org/projects/pyramid/en/latest/api/exceptions.html#pyramid.exceptions.URLDecodeError

The exception view works properly, but we get `AttributeError: 'NoneType' object has no attribute 'finish'` afterwards in baseplate since the request has `None` for the trace.

This was all working fine previously when we were on baseplate 0.28, but this seems to have broken somewhere along the way when we upgraded to 1.0.

I can provide a Sentry exception upon request.
